# Snakemake file for filtering of a VCF file against a set of normal samples.

# Usage: 
# snakemake -p --configfile=config.yaml

import os
import glob
import re

# configfile: 'config.yaml'

rule all:
    input:
        expand('work/filter/{sample}-ann-n{ht}.vcf.gz', sample=config['samples'], ht=config['hits_thresholds'])

# rule prep_vcfanno:
#     input:
#         normals_dir = config['normals_dir']
#     output:
#         toml = 'work/normals/annotate_normals_vcfanno.toml'
#     run:
#         fpaths = glob.glob(os.path.join(input.normals_dir, '*.vcf.gz'))
#         with open(output[0], 'w') as out:
#             for fp in fpaths:
#                 out.write(VCFANNO_ANNO.format(
#                     fname=fp, 
#                     name=str_to_lua_variable_name(fp)))

#             out.write(VCFANNO_POSTANNO.format(
#                 fields=', '.join('"' + str_to_lua_variable_name(fp) + '"' for fp in fpaths), 
#                 vars=', '.join(str_to_lua_variable_name(fp) for fp in fpaths)))

rule prep_vcf:
    input:
        lambda wildcards: config['samples'][wildcards.sample]
    output:
        'work/prep_vcf/{sample}.vcf.gz'
    shell:
        'bcftools view {input} -f.,PASS -Oz -o {output}'

# rule annotate:
#     input:
#         vcf = rules.prep_vcf.output,
#         toml = rules.prep_vcfanno.output.toml
#     output:
#         'work/annotate/{sample}-ann.vcf.gz'
#     params:
#         lua = os.path.join(config['normals_dir'], 'code.lua')
#     shell:
#         'vcfanno -lua {params.lua} {input.toml} {input.vcf} | bgzip -c > {output}'

rule annotate:
    input:
        vcf = rules.prep_vcf.output,
        toml = os.path.join(config['normals_dir'], 'annotate_normals_vcfanno.toml'),
        lua = os.path.join(config['normals_dir'], 'code.lua')
    output:
        'work/annotate/{sample}-ann.vcf.gz'
    shell:
        'vcfanno -lua {input.lua} {input.toml} {input.vcf} | bgzip -c > {output}'

rule filter:
    input:
        rules.annotate.output
    output:
        'work/filter/{sample}-ann-n{ht}.vcf.gz'
    params:
        ht = lambda wildcards: wildcards.ht
    shell:
        'bcftools filter -e "INFO/PoN_CNT>={params.ht}" {input} -Oz -o {output} && tabix -p vcf {output}'













