FROM umccr/umccrise:latest
MAINTAINER Vlad Saveliev "https://github.com/vladsaveliev"

# Run tests; automatically downloads test data
COPY tests/umccrise_test_data/data $TEST_DATA_PATH/data

RUN ln -s $TEST_DATA_PATH/data/genomes $BCBIO_GENOMES_PATH
RUN ln -s $TEST_DATA_PATH/data/panel_of_normals $PON_PATH

