FROM umccr/umccrise:latest
MAINTAINER Vlad Saveliev "https://github.com/vladsaveliev"

# Copy the test data into the container
COPY /Users/vsaveliev/git/umccr/umccrise_test_data $TEST_DATA_PATH

# Copy the reference data
ENV HSAPIENS=/Users/vsaveliev/googledrive/bio/reference_data/genomes/Hsapiens
COPY $HSAPIENS/GRCh37/seq/GRCh37.fa                             $REF_DATA_PATH/GRCh37/GRCh37.fa
COPY $HSAPIENS/GRCh37/coverage/prioritize/cancer/az300.bed.gz   $REF_DATA_PATH/GRCh37/az300.bed.gz
COPY $HSAPIENS/GRCh37/validation/giab-NA12878/truth_regions.bed $REF_DATA_PATH/GRCh37/truth_regions.bed

# Copy the panel of normals
ENV PON=/Users/vsaveliev/googledrive/bio/extras/panel_of_normals/
COPY $PON/GRCh37/panel_of_normals.indels.vcf.gz     $REF_DATA_PATH/GRCh37/panel_of_normals/panel_of_normals.indels.vcf.gz
COPY $PON/GRCh37/panel_of_normals.indels.vcf.gz.tbi $REF_DATA_PATH/GRCh37/panel_of_normals/panel_of_normals.indels.vcf.gz.tbi
COPY $PON/GRCh37/panel_of_normals.snps.vcf.gz       $REF_DATA_PATH/GRCh37/panel_of_normals/panel_of_normals.snps.vcf.gz
COPY $PON/GRCh37/panel_of_normals.snps.vcf.gz.tbi   $REF_DATA_PATH/GRCh37/panel_of_normals/panel_of_normals.snps.vcf.gz.tbi
