#!/usr/bin/env python
import os
from os.path import isfile, join, dirname, abspath
import click
from umccrise import patient_analysis


@click.command()
@click.argument('bcbio_project', type=click.Path(exists=True))
@click.argument('rule', nargs=-1)
@click.option('-o', 'output_dir', type=click.Path())
def main(bcbio_project, output_dir=None, rule=list()):
    cmd = (f'snakemake ' +
           f'{" ".join(rule)} ' +
           f'--snakefile {join(patient_analysis.package_path(), "Snakefile")} ' +
           f'--printshellcmds ' +
          (f'--directory {output_dir} ' if output_dir else ' ') +
           f'--config run_dir={bcbio_project} '
           )
    print(cmd)
    os.system(cmd)


if __name__ == '__main__':
    main()
