#!/usr/bin/env python
import os
import sys
from os.path import isfile, join, dirname, abspath
import click
from umccrise import patient_analysis
from ngs_utils.call_process import run
import subprocess


@click.command()
@click.argument('bcbio_project', type=click.Path(exists=True))
@click.argument('rule', nargs=-1)
@click.option('-o', 'output_dir', type=click.Path())
@click.option('-j', 'jobs', default=1)
@click.option('-s', '--sample', 'sample')
@click.option('-s', '--batch', 'batch')
@click.option('-u', '--pcgr-upload/--no-pcgr-upload', '--upload-pcgr/--no-upload-pcgr', 'upload_pcgr', default=False)
def main(bcbio_project, rule=list(), output_dir=None, jobs=1, sample=None, batch=None, upload_pcgr=False):

    bcbio_project = os.path.abspath(bcbio_project)

    conf = f'run_dir={bcbio_project}'
    if sample:
        conf += f' sample={sample}'
    if batch:
        conf += f' batch={batch}'
    if upload_pcgr:
        conf += f' upload_pcgr=True'

    output_dir = output_dir or 'umccrised'

    cmd = (f'snakemake ' +
        f'{" ".join(rule)} ' +
        f'--snakefile {join(patient_analysis.package_path(), "Snakefile")} ' +
        f'--printshellcmds ' +
        f'--directory {output_dir} ' +
        f'-j {jobs} ' +
        f'--config {conf} ')
    print(cmd)
    exit_code = subprocess.call(cmd, shell=True)
    if exit_code != 0:
        sys.stderr.write('--------\n')
        sys.stderr.write(f'Error running Umccrise: snakemake returned a non-zero status.\n')
        sys.exit(exit_code)

    # Cleanup
    work_dir = join(output_dir, 'work')
    # if isdir(work_dir):
    #     shutils.rmtree(work_dir)


if __name__ == '__main__':
    main()
