---
title: "Purple: bcbio vs umccrise"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: readable
    toc: true
    toc_float: true
    code_folding: hide
  rmdformats::material:
    highlight: kate
params:
  workdir: '/Users/vsaveliev/git/umccr/umccrise/umccrise/rmd_files/purple'
  key_genes: '/Users/vsaveliev/git/NGS_Utils/ngs_utils/reference_data/key_genes/key_genes.txt'
  cancermine: '/Users/vsaveliev/git/NGS_Utils/ngs_utils/reference_data/cancermine_collated.tsv'
---

```{r load-pkgs, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(knitr)
library(rmarkdown)
library(purrr)
library(tidyr)
library(dplyr)
library(readr)
library(DT)
```

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = params$workdir)
```

```{r render_interactively, eval=FALSE, echo=FALSE, warning=FALSE}
# helper function to run report interactively, instead of via the CL.
render_me <- function() {
  rmarkdown::render(
    '/Users/vsaveliev/git/umccr/umccrise/umccrise/rmd_files/purple_bcbio_umccrise.Rmd', 
    output_file = '/Users/vsaveliev/git/umccr/umccrise/umccrise/rmd_files/purple_bcbio_umccrise.html',
    params = list(
      workdir = '/Users/vsaveliev/git/umccr/umccrise/umccrise/rmd_files/purple',
      key_genes = '/Users/vsaveliev/git/NGS_Utils/ngs_utils/reference_data/key_genes/key_genes.txt',
      cancermine = '/Users/vsaveliev/git/NGS_Utils/ngs_utils/reference_data/cancermine_collated.tsv'
    )
  )
}

render_me()
```

```{r load_ref_data, message=FALSE, echo=FALSE, warning=FALSE}
key_genes <- readr::read_tsv(params$key_genes, col_names = "gene", col_types = "c")$gene
cancermine <- readr::read_tsv(params$cancermine) %>%
  mutate(gene = gene_normalized,
         umccr_list = gene %in% key_genes)
oncogenes <- cancermine %>% filter(role == "Oncogene")
tsgenes <- cancermine %>% filter(role == "Tumor_Suppressor")
```

```{r read_files, message=FALSE, echo=FALSE, warning=FALSE}
read_plus <- function(fn) {
    readr::read_tsv(fn, col_types = "ciicd") %>% dplyr::mutate(fname = fn)
}
bcbio <-
    list.files(pattern = "^bcbio_") %>% 
    map_df(~read_plus(.)) %>%
    dplyr::mutate(pipeline = "bcbio")
umccrise <- 
    list.files(pattern = "^umccrise_") %>% 
    map_df(~read_plus(.)) %>%
    dplyr::mutate(pipeline = "umccrise")
```

```{r build_data}
data <- rbind(bcbio, umccrise) %>% 
  dplyr::select(fname, Gene, MinCopyNumber, pipeline) %>% 
  mutate(sample = gsub("\\.purple.gene.cnv$", "\\1", fname)) %>% 
  mutate(sample = gsub("^(bcbio_|umccrise_)", "\\2", sample)) %>% 
  filter(Gene %in% key_genes) %>% 
  dplyr::mutate(gene = Gene,
                role = ifelse(gene %in% oncogenes$gene, 'oncogene', ifelse(gene %in% tsgenes$gene, 'tsgene', '')),
                event = ifelse(MinCopyNumber < 0.5, 'hom_del',
                               ifelse(MinCopyNumber < 1.5, 'het_del',
                               ifelse(MinCopyNumber > 3.5, 'gain', ''))),
                min_cn = MinCopyNumber) %>%
  dplyr::select(gene, pipeline, sample, min_cn, event)

purple <- data %>% 
  arrange(gene, sample) %>%
  group_by(gene, sample) %>% 
  summarize(event_bcbio = nth(event, 1),
            event_umccrise = nth(event, 2),
            cn_bcbio = nth(min_cn, 1),
            cn_umccrise = nth(min_cn, 2),
            match_event = event_bcbio == event_umccrise,
            match_cn = near(cn_bcbio, cn_umccrise, 0.5))

non_matching <- 
  purple %>% 
  filter(!match_event | !match_cn)

smr <- purple %>% 
  group_by(sample) %>% 
  summarize(match_event = mean(match_event),
            match_cn = mean(match_cn)
  )
```

### Genes and samples with mismatching bcbio/umccrise calls

- "match_event" means that the inferered event (hom_del, het_del, gain) is the same in bcbio and umccrise
- "match_cn" means that the CN number matches within 0.5 tolerance

```{r non_matching}
DT::datatable(non_matching)
```

### For each sample, proportion of genes with matching calls

```{r summary}
DT::datatable(smr)
```







