# Session Info

<details>
<summary>R packages</summary>
```{r eval=TRUE}
si <- devtools::session_info(include_base = TRUE)
si_pl <- unclass(si$platform) %>% as_tibble() %>% t()
si_pkg <- unclass(si$packages) %>% 
  dplyr::as_tibble() %>% 
  dplyr::select(package, version = ondiskversion, path, datestamp = date)

  

dplyr::tibble(var = row.names(si_pl), 
              value = si_pl[, , drop = TRUE]) %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>% 
  kableExtra::column_spec(1, bold = TRUE)

knitr::kable(si_pkg, format = "html") %>% 
  kableExtra::kable_styling(full_width = TRUE, position = "left") %>% 
  kableExtra::column_spec(1, bold = TRUE)
```
</details>

<details>
<summary>conda packages</summary>

```{r eval=FALSE}
which_r <- Sys.which("R")
conda_bin <- list.files(file.path(dirname(dirname(dirname(dirname(x)))), "bin"), 
                        pattern = "^conda$", full.names=T)
conda_list <- system(command = paste(conda_bin, "list"), intern = TRUE)
conda_list # do pretty stuff with it
```

</details>
