# Teeny-tiny matplotlib image based on alpine
FROM czentye/matplotlib-minimal:3.0.3

RUN apk add --no-cache bash

# Add the MultiQC source files to the container
ADD . /usr/src/multiqc
WORKDIR /usr/src/multiqc

# Install MultiQC
RUN python setup.py install

# Set up entrypoint and cmd for easy docker usage
ENTRYPOINT [ "multiqc" ]
CMD [ "." ]
