# PCGR configuration options (TOML).

[tier_model]
## tier model for prioritization of SNVs/InDels ("pcgr_acmg" or "pcgr")
tier_model = "pcgr_acmg"

[tumor_only]
# If input VCF contains mix of germline/somatic (variants called with no matching control, i.e. tumor-only) set vcf_tumor_only to true
vcf_tumor_only = false

# set VCF INFO columns (tags) that contains tumor sequencing depth at variant
# site (tumor_dp_tag), tumor variant allelic fraction (tumor_af_tag) etc.
[allelic_support]
## Specify INFO tags in input VCF that denotes depth/allelic fraction in tumor and normal sample
## An additional tag that denotes call confidence (call_conf_tag) can also be specified, which will
## be used for exploration in the global variant browser. Note that 'tumor_dp_tag' must be of
## Type=Integer, and 'tumor_af_tag' must be of Type=Float (similarly for normal sample)
tumor_dp_tag = "TUMOR_DP"
tumor_af_tag = "TUMOR_AF"
normal_dp_tag = "NORMAL_DP"
normal_af_tag = "NORMAL_AF"
call_conf_tag = "_na"

## set thresholds for tumor depth/allelic fraction, will be applied before report generation
## requires that 'tumor_dp_tag' and 'tumor_tag' are specified above
tumor_dp_min = 0
tumor_af_min = 0.0
normal_dp_min = 0
normal_af_max = 1.0

[mutational_burden]
## Calculate mutational burden (similar to Chalmers et al., Genome Med, 2017)
mutational_burden = true
## Size of coding target region in megabases (defaults to exome ~ 36 Mb)
## Note: this should ideally denote the callable target size (i.e. reflecting variable
## sequencing depth)
target_size_mb = 34.0
## set upper limits to tumor mutational burden tertiles (mutations/Mb)
tmb_low_limit = 5
tmb_intermediate_limit = 20
## tmb_high = tmb > tmb_intermediate_limit

[msi]
## Predict microsatellite instability
msi = true

[visual]
## Choose visual theme of report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = "default"

[custom_tags]
## list VCF info tags that should be present in JSON and TSV output
## tags should be comma separated, i.e. custom_tags = "MUTECT2_FILTER,STRELKA_FILTER"
custom_tags = ""

[other]
## list/do not list noncoding variants
list_noncoding = true
## Customise the order of criteria used to pick the primary transcript in VEP (see https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order)
vep_pick_order = "biotype,rank,appris,tsl,ccds,canonical,length,mane"
## VEP/vcfanno processing options
n_vcfanno_proc = 4
n_vep_forks = 4
## omit intergenic variants during VEP processing
vep_skip_intergenic = false
## generate a MAF for input VCF using https://github.com/mskcc/vcf2maf
vcf2maf = false

[tumor_type]
type = ""
