#!/usr/bin/env python

import os
import platform
import sys
import glob
from os.path import isfile, join, dirname, abspath, basename, exists
import click
import subprocess

from ngs_utils.call_process import run_simple
from ngs_utils.file_utils import verify_file, safe_mkdir, splitext_plus
from ngs_utils import logger
from ngs_utils.logger import info, critical, err
from ngs_utils.utils import set_locale; set_locale()

@click.command()
@click.argument('vcf_path', type=click.Path(exists=True))
@click.option('-o', 'output_dir', required=True, type=click.Path())
@click.option('-s', 'sample')
@click.option('--pcgr-data', type=click.Path(exists=True), help='Path to PCGR data directory')
@click.option('--predispose-genes', 'predispose_genes', type=click.Path(exists=True), help='Path to CPSR gene panel')
@click.option('--genomes-dir', 'genomes_dir')
@click.option('--pcgrr-conda', 'pcgrr_conda')
def main(vcf_path, output_dir, sample=None, pcgr_data=None, predispose_genes=None,
         genomes_dir=None, pcgrr_conda="pcgrr"):

    genome = {'pcgr': 'grch38', 'refdata': 'hg38'}
    if not pcgr_data:
        from reference_data import api as refdata
        if genomes_dir:
            refdata.find_genomes_dir(genomes_dir)
        pcgr_data = refdata.get_ref_file(genome=genome['refdata'], key='pcgr_data')
        if not pcgr_data:
            logger.critical(f'PCGR data is not found on the system "{refdata.name}".'
                            f' Please, provide the path to PCGR data with --pcgr-data.')

    # compress and index input vcf
    if vcf_path.endswith('.vcf'):
        run_simple(f'bgzip {vcf_path}')
        vcf_path = vcf_path + '.gz'
    if not isfile(vcf_path + '.tbi'):
        run_simple(f'tabix -p vcf {vcf_path}')

    output_dir = abspath(output_dir)
    safe_mkdir(output_dir)
    logger.init(log_fpath_=join(output_dir, 'um_cpsr_log.txt'), save_previous=True)

    sample = sample or splitext_plus(basename(vcf_path))[0]
    sample_cropped = sample[:35]  # pcgr requires sample names shorter than 35

    expected_file_base = join(output_dir, f'{sample_cropped}.cpsr.{genome["pcgr"]}')
    renamed_file_base = join(output_dir, f'{sample}.cpsr')
    panel_param = '--panel_id 0'
    if predispose_genes:
        panel_param = f'--custom_list {predispose_genes} --custom_list_name "umccr_predisposition_panel"'

    cmd = (f'cpsr '
           f'--input_vcf {abspath(vcf_path)} '
           f'--sample_id {sample_cropped} '
           f'--pcgr_dir {dirname(pcgr_data)} '
           f'--output_dir {output_dir} '
           f'--genome_assembly {genome["pcgr"]} '
           f'--pop_gnomad "global" '
           f'--vep_buffer_size 5000 '
           f'--vep_pick_order "biotype,rank,appris,tsl,ccds,canonical,length,mane" '
           f'--report_theme "default" '
           f'--pcgrr_conda {pcgrr_conda} '
           f'--force_overwrite '
           f'{panel_param} '
       )
    try:
        run_simple(cmd)
    except subprocess.SubprocessError:
        err('--------\n')
        err('ERROR running CPSR.\n')
        raise

    err('Finished CPSR.\n')
    for expected_fpath in glob.glob(f'{expected_file_base}*'):
        if isfile(expected_fpath):
            renamed_fpath = expected_fpath.replace(expected_file_base, renamed_file_base)
            os.rename(expected_fpath, renamed_fpath)
            if renamed_fpath.endswith('.html'):
                info(f'CPSR report: {renamed_fpath}')


if __name__ == '__main__':
    main()
